### ISSUE TITLE
Data Writer component is broken

### ISSUE THREAD

**Issue by michelboaventura** [eubr-bigsea/citron#251]
Creating a Data Writer operation and clicking on it produces:

```
ember.debug.js:19829 Assertion Failed: Could not find component named "forms/form-tag" (no component or template with that name was found)
Error
    at assert (http://localhost:4200/assets/vendor.js:18611:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:18824:34)
    at DynamicComponentReference.value (http://localhost:4200/assets/vendor.js:25820:21)
    at ReferenceCache.initialize (http://localhost:4200/assets/vendor.js:11344:52)
    at ReferenceCache.peek (http://localhost:4200/assets/vendor.js:11318:29)
    at http://localhost:4200/assets/vendor.js:11675:2938
    at AppendOpcodes.evaluate (http://localhost:4200/assets/vendor.js:11674:2168)
    at VM.next (http://localhost:4200/assets/vendor.js:11925:872)
    at VM.execute (http://localhost:4200/assets/vendor.js:11925:280)
    at VM.resume (http://localhost:4200/assets/vendor.js:11925:68)
```

**Comment by michelboaventura** [comment]
It seems it is using a new widget: ``form-tag`` which doesn't exist yet. @waltersf, do you have an example of this widget?

**Comment by waltersf** [comment]
@michelboaventura No, I don't have an example. But you can consider using a Select2, for instance. It is an input to inform tags for a data set
